# Generated by Django 3.2.20 on 2025-09-04 00:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(default='financogram_user', max_length=20, unique=True)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('face_image', models.URLField(blank=True, max_length=500, null=True)),
                ('profile_image', models.URLField(blank=True, max_length=500, null=True)),
                ('qr_code', models.URLField(blank=True, max_length=500, null=True)),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('balance', models.CharField(default='0.00', max_length=10)),
            ],
        ),
    ]
