# Generated by Django 3.2.20 on 2025-08-03 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('fund_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('pan', models.CharField(max_length=10)),
                ('investment_type', models.CharField(max_length=20)),
                ('nav', models.FloatField()),
                ('category', models.CharField(max_length=255)),
                ('risk', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_mode', models.CharField(max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
