# Generated by Django 3.2.20 on 2025-08-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='pan',
        ),
        migrations.AddField(
            model_name='investment',
            name='sip_date',
            field=models.CharField(default='Not Applicable', max_length=2),
        ),
    ]
